version: 2.1

# 1. Define the individual Jobs
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0 
    steps:
      - checkout
      # 'mvn compile' only checks if the code is valid and compiles it
      - run:
          name: Compile Project
          command: mvn compile
      # This saves the compiled code so the next job can use it
      - persist_to_workspace:
          root: .
          paths:
            - .
      # Store compiled .class files as artifacts
      - store_artifacts:
          path: target/classes
          destination: compiled-classes


  test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      # This retrieves the compiled code from the build job
      - attach_workspace:
          at: .
      - run:
          name: Run JUnit Tests
          command: mvn test
      
       # Store test reports
      - store_artifacts:
          path: target/surefire-reports
          destination: test-reports
      
  
  package:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Package Project
          command: |
            echo "Packaging Project Version 2.1"
            mvn package
            mkdir -p ~/deployments
            cp target/*.jar ~/deployments/
            echo "Package completed"

        # Store the built .jar as an artifact
      - store_artifacts:
          path: ~/deployments
          destination: jar-files

# 2. Orchestrate them in a Workflow
workflows:
  school-system-pipeline:
    jobs:
      - build
      - test:
          requires:
            - build # This ensures 'test' waits for 'build' to finish successfully   
      - package:
          requires:
            - test